CREATE DATABASE formas;

USE formas;

CREATE TABLE quadrado (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lado FLOAT NOT NULL
);

ALTER TABLE quadrado ADD COLUMN cor VARCHAR(7) NOT NULL DEFAULT '#FFFFE0';

